use crate::model::SystemSnapshot;
use chrono::{DateTime, Local};

const REDACTED: &str = "[redacted]";

pub fn to_json(snapshot: &SystemSnapshot, pretty: bool, include_sensitive: bool) -> String {
    let cleaned = if include_sensitive {
        snapshot.clone()
    } else {
        redact(snapshot.clone())
    };
    if pretty {
        serde_json::to_string_pretty(&cleaned).unwrap_or_else(|_| String::from("{}"))
    } else {
        serde_json::to_string(&cleaned).unwrap_or_else(|_| String::from("{}"))
    }
}

fn redact(mut s: SystemSnapshot) -> SystemSnapshot {
    // 主板 / 电池 / 存储序列号
    if let Some(mb) = s.motherboard.as_mut() {
        mb.serial = mb.serial.as_ref().map(|_| REDACTED.to_string());
    }
    for st in s.storages.iter_mut() {
        st.serial = st.serial.as_ref().map(|_| REDACTED.to_string());
    }
    // 网卡 MAC
    for n in s.network.interfaces.iter_mut() {
        n.mac = n.mac.as_ref().map(|_| REDACTED.to_string());
    }
    // 主机名 / 用户名（弱敏感，但跨设备可识别）
    s.host.hostname = REDACTED.to_string();
    s.host.username = REDACTED.to_string();
    // 内存条序列号在 part_number 之外可能存在；当前 model 不含 serial 字段，跳过
    // 公网 IP：如果存在则 redact
    s.network.public_ip = s.network.public_ip.as_ref().map(|_| REDACTED.to_string());
    s
}

fn fmt_ts(ms: u64) -> String {
    let dt = DateTime::<Local>::from(
        std::time::UNIX_EPOCH + std::time::Duration::from_millis(ms),
    );
    dt.format("%Y-%m-%d %H:%M:%S %Z").to_string()
}

fn fmt_bytes(n: u64) -> String {
    const UNITS: [&str; 6] = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"];
    let mut v = n as f64;
    let mut i = 0;
    while v >= 1024.0 && i < UNITS.len() - 1 {
        v /= 1024.0;
        i += 1;
    }
    if i == 0 {
        format!("{n} {}", UNITS[0])
    } else {
        format!("{:.1} {}", v, UNITS[i])
    }
}

fn opt_str<S: AsRef<str>>(o: &Option<S>) -> &str {
    o.as_ref().map(|v| v.as_ref()).unwrap_or("—")
}

pub fn to_markdown(snapshot: &SystemSnapshot, include_sensitive: bool) -> String {
    let cleaned;
    let s = if include_sensitive {
        snapshot
    } else {
        cleaned = redact(snapshot.clone());
        &cleaned
    };
    let mut out = String::new();
    out.push_str("# PC Specs Report\n\n");
    out.push_str(&format!(
        "_Generated by PC Specs v{} at {}{}_\n\n",
        s.host.app_version,
        fmt_ts(s.timestamp),
        if include_sensitive { " · with sensitive data" } else { " · sanitized" },
    ));

    out.push_str("## Host\n\n");
    out.push_str(&format!("- Hostname: `{}`\n", s.host.hostname));
    out.push_str(&format!("- User: `{}`\n", s.host.username));
    out.push_str(&format!("- Uptime: {}s\n", s.host.uptime_secs));

    out.push_str("\n## OS\n\n");
    out.push_str(&format!("- Family: {}\n", s.os.family));
    out.push_str(&format!("- Name: {}\n", s.os.name));
    out.push_str(&format!("- Version: {}\n", s.os.version));
    out.push_str(&format!("- Kernel: {}\n", s.os.kernel));
    out.push_str(&format!("- Arch: {}\n", s.os.arch));
    if let Some(d) = &s.os.desktop {
        out.push_str(&format!("- Desktop: {d}\n"));
    }
    if let Some(sh) = &s.os.shell {
        out.push_str(&format!("- Shell: {sh}\n"));
    }

    out.push_str("\n## CPU\n\n");
    out.push_str(&format!("- Brand: {}\n", s.cpu.brand));
    out.push_str(&format!("- Vendor: {}\n", s.cpu.vendor));
    out.push_str(&format!("- Arch: {}\n", s.cpu.arch));
    out.push_str(&format!(
        "- Cores: {} physical / {} logical\n",
        s.cpu.physical_cores, s.cpu.logical_cores
    ));
    if let Some(t) = &s.cpu.topology {
        if t.p_cores.is_some() || t.e_cores.is_some() {
            out.push_str(&format!(
                "- Topology: P×{} · E×{} · {} numa\n",
                t.p_cores.unwrap_or(0),
                t.e_cores.unwrap_or(0),
                t.numa_nodes
            ));
        }
    }
    out.push_str(&format!(
        "- Frequency: {:.2} GHz (max {:.2} GHz)\n",
        s.cpu.current_frequency_hz as f64 / 1e9,
        s.cpu.max_frequency_hz as f64 / 1e9,
    ));
    if let Some(v) = s.cpu.cache_l1_bytes {
        out.push_str(&format!("- L1 cache: {}\n", fmt_bytes(v)));
    }
    if let Some(v) = s.cpu.cache_l2_bytes {
        out.push_str(&format!("- L2 cache: {}\n", fmt_bytes(v)));
    }
    if let Some(v) = s.cpu.cache_l3_bytes {
        out.push_str(&format!("- L3 cache: {}\n", fmt_bytes(v)));
    }
    if let Some(t) = s.cpu.temperature_c {
        out.push_str(&format!("- Temperature: {:.1}°C\n", t));
    }
    if !s.cpu.features.is_empty() {
        out.push_str(&format!(
            "- Features: {}\n",
            s.cpu.features.iter().take(40).cloned().collect::<Vec<_>>().join(", ")
        ));
        if s.cpu.features.len() > 40 {
            out.push_str(&format!(
                "- Features (more): +{} additional\n",
                s.cpu.features.len() - 40
            ));
        }
    }

    out.push_str("\n## GPUs\n\n");
    if s.gpus.is_empty() {
        out.push_str("_None detected_\n");
    } else {
        for g in &s.gpus {
            out.push_str(&format!(
                "- [{}] **{}** ({}) — backend: {} {}\n",
                g.index,
                g.name,
                g.vendor,
                g.backend,
                if g.is_discrete {
                    "· discrete"
                } else {
                    "· integrated"
                }
            ));
            if let Some(v) = g.vram_total_bytes {
                out.push_str(&format!("    - VRAM: {}\n", fmt_bytes(v)));
            }
            if let Some(p) = &g.pcie_link {
                out.push_str(&format!("    - PCIe: {p}\n"));
            }
            if let Some(d) = &g.driver {
                out.push_str(&format!("    - Driver: {d}\n"));
            }
            if let Some(t) = g.temperature_c {
                out.push_str(&format!("    - Temperature: {:.1}°C\n", t));
            }
            if let Some(u) = g.utilization {
                out.push_str(&format!("    - Utilization: {:.1}%\n", u));
            }
            if let Some(w) = g.power_w {
                out.push_str(&format!("    - Power: {:.1} W\n", w));
            }
        }
    }

    out.push_str("\n## Memory\n\n");
    out.push_str(&format!(
        "- Total: {} · Used: {} · Available: {}\n",
        fmt_bytes(s.memory.total_bytes),
        fmt_bytes(s.memory.used_bytes),
        fmt_bytes(s.memory.available_bytes),
    ));
    out.push_str(&format!(
        "- Swap: {} used / {} total\n",
        fmt_bytes(s.memory.swap_used_bytes),
        fmt_bytes(s.memory.swap_total_bytes),
    ));
    if !s.memory.modules.is_empty() {
        out.push_str("\n| Slot | Manufacturer | Part | Capacity | Speed | Type |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for m in &s.memory.modules {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} |\n",
                m.slot,
                opt_str(&m.manufacturer),
                opt_str(&m.part_number),
                fmt_bytes(m.capacity_bytes),
                m.speed_mt_s
                    .map(|v| format!("{v} MT/s"))
                    .unwrap_or_else(|| "—".into()),
                opt_str(&m.kind),
            ));
        }
    }

    out.push_str("\n## Storage\n\n");
    if s.storages.is_empty() {
        out.push_str("_None detected_\n");
    } else {
        let any_io = s
            .storages
            .iter()
            .any(|d| d.read_bytes_per_sec > 0 || d.write_bytes_per_sec > 0);
        if any_io {
            out.push_str("| Name | Mount | FS | Type | Used / Total | I/O |\n");
            out.push_str("|---|---|---|---|---|---|\n");
            for d in &s.storages {
                out.push_str(&format!(
                    "| {} | {} | {} | {} | {} / {} | R {}/s · W {}/s |\n",
                    d.name,
                    opt_str(&d.mount_point),
                    opt_str(&d.filesystem),
                    d.kind,
                    fmt_bytes(d.used_bytes),
                    fmt_bytes(d.total_bytes),
                    fmt_bytes(d.read_bytes_per_sec),
                    fmt_bytes(d.write_bytes_per_sec),
                ));
            }
        } else {
            out.push_str("| Name | Mount | FS | Type | Used / Total |\n");
            out.push_str("|---|---|---|---|---|\n");
            for d in &s.storages {
                out.push_str(&format!(
                    "| {} | {} | {} | {} | {} / {} |\n",
                    d.name,
                    opt_str(&d.mount_point),
                    opt_str(&d.filesystem),
                    d.kind,
                    fmt_bytes(d.used_bytes),
                    fmt_bytes(d.total_bytes),
                ));
            }
            out.push_str(
                "\n_I/O sampling is currently Linux-only; macOS / Windows show only capacity._\n",
            );
        }
    }

    if let Some(mb) = &s.motherboard {
        out.push_str("\n## Motherboard\n\n");
        out.push_str(&format!("- Vendor: {}\n", opt_str(&mb.vendor)));
        out.push_str(&format!("- Model: {}\n", opt_str(&mb.model)));
        if let Some(v) = &mb.bios_version {
            out.push_str(&format!(
                "- BIOS: {} ({})\n",
                v,
                opt_str(&mb.bios_date)
            ));
        }
        out.push_str(&format!("- Chassis: {}\n", opt_str(&mb.chassis)));
    }

    out.push_str("\n## Network\n\n");
    if let Some(g) = &s.network.default_gateway {
        out.push_str(&format!("- Default gateway: `{g}`\n"));
    }
    if !s.network.dns_servers.is_empty() {
        out.push_str(&format!("- DNS: {}\n", s.network.dns_servers.join(", ")));
    }
    if let Some(ip) = &s.network.public_ip {
        out.push_str(&format!("- Public IP: `{ip}`\n"));
    }
    if s.network.interfaces.is_empty() {
        out.push_str("_No interfaces_\n");
    } else {
        out.push_str("\n| Name | Kind | IPv4 | MAC | Up |\n");
        out.push_str("|---|---|---|---|---|\n");
        for n in &s.network.interfaces {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                n.name,
                n.kind,
                if n.ipv4.is_empty() {
                    "—".into()
                } else {
                    n.ipv4.join(", ")
                },
                opt_str(&n.mac),
                if n.is_up { "yes" } else { "no" },
            ));
        }
    }

    if !s.displays.is_empty() {
        out.push_str("\n## Displays\n\n");
        for d in &s.displays {
            out.push_str(&format!(
                "- {} — {}×{}{}{}\n",
                d.name,
                d.width_px,
                d.height_px,
                d.refresh_hz
                    .map(|h| format!(" @ {h}Hz"))
                    .unwrap_or_default(),
                if d.is_primary { " · primary" } else { "" },
            ));
        }
    }

    out.push_str("\n## Sensors\n\n");
    if s.sensors.is_empty() {
        out.push_str("_No sensor data_\n");
    } else {
        for r in &s.sensors {
            out.push_str(&format!(
                "- [{}] {}: {:.1} {}\n",
                r.source, r.label, r.value, r.unit
            ));
        }
    }

    if let Some(b) = &s.battery {
        out.push_str("\n## Battery\n\n");
        out.push_str(&format!("- State: {}\n", b.state));
        out.push_str(&format!("- Percentage: {:.1}%\n", b.percentage));
        if let Some(c) = b.cycle_count {
            out.push_str(&format!("- Cycle count: {c}\n"));
        }
        if let (Some(d), Some(f)) = (b.design_capacity_mwh, b.full_capacity_mwh) {
            let health = if d > 0 {
                f as f64 * 100.0 / d as f64
            } else {
                0.0
            };
            out.push_str(&format!(
                "- Capacity: {} mWh full / {} mWh design ({:.0}% health)\n",
                f, d, health
            ));
        }
        if let Some(t) = b.temperature_c {
            out.push_str(&format!("- Temperature: {:.1}°C\n", t));
        }
        if let Some(p) = b.power_now_mw {
            out.push_str(&format!("- Power: {:.2} W\n", p as f64 / 1000.0));
        }
    }

    if !s.peripherals.is_empty() {
        out.push_str("\n## Peripherals\n\n");
        out.push_str("| Kind | Name | Vendor | Product | Bus |\n");
        out.push_str("|---|---|---|---|---|\n");
        for p in &s.peripherals {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                p.kind,
                p.name,
                opt_str(&p.vendor_id),
                opt_str(&p.product_id),
                opt_str(&p.bus),
            ));
        }
    }

    out.push_str("\n## Dev Environment\n\n");
    let de = &s.dev_env;
    let mut writer = |title: &str, list: &Vec<crate::model::RuntimeInfo>| {
        if list.is_empty() {
            return;
        }
        out.push_str(&format!("### {title}\n\n"));
        for r in list {
            out.push_str(&format!(
                "- **{}** {}\n",
                r.name,
                opt_str(&r.version)
            ));
        }
        out.push('\n');
    };
    writer("Languages", &de.languages);
    writer("Package Managers", &de.package_managers);
    writer("VCS", &de.vcs);
    writer("Editors", &de.editors);
    writer("Containers", &de.containers);
    writer("Shells", &de.shells);

    out
}
